前編 作成完了
tkms0106/e-navigator pull request #1
Opened 2018-03-29 14:13 UTC by tkms0106

## やりたかったこと

- ユーザー登録、ログイン機能の追加
- 登録したユーザーのプロフィール編集機能の追加

## やったこと

- Devise gem の導入
- Userモデルへプロフィール情報（名前、生年月日、性別、学校）を追加
- Usersコントローラを追加
- ユーザー一覧ページ、ユーザープロフィール編集ページを追加
- Userモデルへ年齢を表すage属性を追加
- 年齢を生年月日から計算し、負の年齢を受け付けないバリデーションにより、プロフィールで未来の日付を入力できない制限を追加
- deviseの提供するフィルターにより、未ログイン状態でのユーザー一覧ページ・プロフィール編集ページへのアクセスとプロフィール更新操作を防止

## 動作確認方法

- [ ] ユーザーを新規で作成する
- [ ] [プロフィール]リンクからプロフィールの編集ページにいく
- [ ] プロフィールを編集・更新する（正常）
  - [ ] 名前と学校欄に文字列を入力する
  - [ ] 生年月日に今日以前の日付を入力する
  - [ ] 性別をプルダウンメニューから選択する
  - [ ] "プロフィールを更新"ボタンを押す
  - [ ] 再びプロフィール編集ページに行き、入力内容が反映されていることを確認する
- [ ] プロフィールを編集・更新する（異常）
  - [ ] 生年月日に明日以降の日付を入力する
  - [ ] "プロフィールを更新"ボタンを押す
  - [ ] 再びプロフィール編集ページに行き、入力内容が反映されていないことを確認する
- [ ] ログアウトした状態で`https://e-navigator-tkms0106.herokuapp.com/users/`にアクセスしてもユーザー一覧は表示されず`/users/sign_in`に戻されることを確認する

## その他

一旦できたと思ってから、

>生年月日を登録しておけば年齢は計算できますね

この文章を見返して「そういえば年齢の計算なんてしていないけど、これはどういうことだろう」と思い、生年月日に未来の日付を登録できない制限を加えてみました。

2018-03-30 02:32 UTC, pokotyamu commented
見ます 👀

2018-03-30 02:34 UTC, pokotyamu commented
git の使い方(コミットメッセージ)完璧ですね 👍 
特に、実行したコマンドでコミット分けているのが良いと思います！！3a09572 とか 08a2b0b とか 👍

2018-03-30 02:39 UTC, pokotyamu commented
ただ、プルリクエストの作り方としては、ちょっと直して欲しいです。

![_2018_03_30_11_34](https://user-images.githubusercontent.com/3479317/38122146-52f49d76-340e-11e8-860e-cc73776c7f37.png)

まず、タイトルですが、このプルリクエストでなにがしたかったのかを書きましょう！
今回で言えば、ログイン機能とかユーザー追加とかが主題になりそうですね 👀 

またブランチ名も first-part ではなく、タイトルを英語に訳してみたものなどを付けると良いです。

なぜこんなことをするかというと、過去のプルリクエストを振り返った時に、タイトルだけでこのプルリクエストで何をしたかったのか分かるようにしてほしいためです！
タイトルはサクッと変えれるので今回修正してください。ブランチ名は次回からで大丈夫です😄

2018-03-30 05:15 UTC, pokotyamu requested changes
細かい部分の指摘も含んでますが修正よろしくお願いします！

2018-03-30 05:15 UTC, pokotyamu commented on app/views/layouts/application.html.erb
> +    <%= debug(params) if Rails.env.development? %>
うーん 🤔 
debug 用のコードを本番に残しておくのはあんまりよろしくないですね。
必要に応じて開発時に書く、本番には書かないというのをやってほしいです。

なので、これは消して下さい 🙏

2018-03-30 05:15 UTC, pokotyamu commented on config/routes.rb
> +  resources :users, only: [:index, :edit, :update]
resources で必要なリソースだけ only で指定するのいいですね 👍

2018-03-30 05:15 UTC, pokotyamu commented on app/models/user.rb
> +  validates :age, numericality: { greater_than_or_equal_to: 0 }
【余談】
ここで年齢計算した結果に対してバリデーションしてますが、生年月日の日付が現在より未来ならバリデーション違反というのでも良さそうな気がしました！

2018-03-30 05:15 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    end
全体的に if/unless 文に対して then を書いてますがこれは省略可能ですね 👀 
また Ruby の記法として１行にまとめて書く後置 if というものもあります

```
flash[:alert] = 'Failed to update profile.' unless current_user.update_attributes(user_params)
```

2018-03-30 05:15 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    unless current_user.update_attributes(user_params) then
間違いではないのですが、update_attributes は update の alias なので、 update を使いましょう 👀

2018-03-30 05:15 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    @user = current_user
`edit_user GET    /users/:id/edit(.:format)      users#edit`  
というルーティング的に、 id = n 番のユーザーについての編集可と思いきや、 current_user なんですね 👀 
User.find(id) を使った形にして、id とカレントユーザーが一致しなかったら、 index に戻すなどで対応しても良さそうに思いました。

2018-04-03 03:53 UTC, pokotyamu commented
> d09077e

内容の変更なしというコミットコメントですが、コメントを消してますよね。
そのコミットで何をしたか？が重要なので、`コメントの削除` とかの方が良さそうです！(修正はしなくて大丈夫です)

----

【余談】
デフォルトのコメントは使い方など参考情報として使えるものが多いので、なるべく消さない方が良いかと思いますよ😄

2018-04-03 03:56 UTC, pokotyamu requested changes

2018-04-03 03:56 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +  before_action :correct_user, only: [:edit, :update]
corrent_user -> current_user の typo ですかね？
current_user は devise のメソッドと被ってしまうため、 set_user とかって名前の方が適切かと思います。
パラメーターの id のレコードを DB から取って来る時によく、 set_XXX というのを使います！(XXX はモデル名)

2018-04-03 04:01 UTC, pokotyamu commented
ご参考までに↓
[【今日からできる】コミットメッセージに 「プレフィックス」 をつけるだけで、開発効率が上がった話 - Qiita](https://qiita.com/numanomanu/items/45dd285b286a1f7280ed)

prefix めっちゃ良いと思います！
なんで、オリジナルな感じでなく、広く使われているのに合わせるというのも良さそうに思ったので、共有しますね😊
実際ここらへんは、チーム単位で揃っておけばいいと思うので、参考程度で良いです🙋‍♂️

2018-04-03 10:22 UTC, tkms0106 commented on app/controllers/users_controller.rb
> +  before_action :correct_user, only: [:edit, :update]
ありがとうございます。参考にします。

2018-04-03 10:25 UTC, tkms0106 commented
コミットメッセージの記事もありがとうございます。

現状のプレフィックスの付け方は、以下の記事を真似ていました。
[Gitのコミットメッセージの書き方](https://qiita.com/itosho/items/9565c6ad2ffc24c09364)

2018-04-03 10:26 UTC, merged

2018-04-04 01:32 UTC, pokotyamu commented
> 現状のプレフィックスの付け方は、以下の記事を真似ていました。
Gitのコミットメッセージの書き方

元ネタ知れてよかったです 🙆‍♂️ 
今後も続けてみて下さい 👍