面接日程の一覧表示および登録
tkms0106/e-navigator pull request #2
Opened 2018-04-16 11:54 UTC by tkms0106

## やりたかったこと

- 面接日程一覧表示機能の追加
- 面接日程登録機能の追加

## やったこと

- Interviewモデルの追加
- Interviewsコントローラの追加
- UserモデルとInterviewモデルの関連付け
- 面接日程一覧表示機能の実装 Interviews#index
- 面接日程登録機能の実装 Interviews#new, create
- ユーザー・面接間の１対多の紐付きを反映したルーティング
- アプリケーションのタイムゾーン設定
- Interviewsコントローラのアクションに対するフィルター設定
- ユーザーの性別への値の割り当て方を変更

## 動作確認方法

- [ ] （ユーザーを新規で作成する）
- [ ] ログインする
- [ ] [自分の面接一覧]リンクから面接一覧ページに遷移する
  - [ ] 「面接日程がありません。」と表示される
- [ ] "面接日程作成"リンクから面接登録ページに遷移する
- [ ] 年月日および時刻を入力し、"作成"ボタンを押す
  - [ ] 面接一覧ページに自動的に遷移し、登録した日程が表示される

※以下は性別に関する変更分

- [ ] [プロフィール]リンクからプロフィール編集ページに遷移する
  - [ ] 以前のバージョンで「男性」だった場合空欄、「女性」だった場合男性、「不明」だった場合女性になっている

## その他

性別の扱いについて変更したのは、以下記事に影響を受けたためです。
[システムで「性別」の情報を扱う前に知っておくべきこと - Qiita](https://qiita.com/aoshirobo/items/32deb45cb8c8b87d65a4#%E7%B5%90%E8%AB%96)

2018-04-19 05:05 UTC, pokotyamu commented
見ます 👀

2018-04-19 05:30 UTC, pokotyamu commented
> 性別の扱いについて変更したのは、以下記事に影響を受けたためです。
> システムで「性別」の情報を扱う前に知っておくべきこと - Qiita

良いですね 👍 
なぜこうしたのかというのを明確に書いていただけて助かります 🙏

2018-04-19 05:33 UTC, pokotyamu requested changes
@tkms0106 ２点修正して欲しい点と、確認して欲しい点をコメントしています。
返答よろしくお願いします 🙏

2018-04-19 05:33 UTC, pokotyamu commented on app/models/interview.rb
> +  belongs_to :user
関連付けは上手く出来てますが、このままだと、 Interview に紐づく User が消えた場合、 Interview のレコードが残り続けてしまいます。
なんで、この部分は連動して削除されるように修正よろしくお願いします 🙏

2018-04-19 05:33 UTC, pokotyamu commented on db/schema.rb
> +    t.boolean "is_available"
この２つのカラムには null 制約付けなくてもいいですか？ 🤔 
`is_available` => null の状態が保留中という意味でしょうか？

2018-04-19 10:33 UTC, tkms0106 commented on db/schema.rb
> +    t.boolean "is_available"
はい。
null: 保留中
true: 承認
false: 拒否
として扱うつもりでした。

2018-04-19 10:35 UTC, tkms0106 commented on app/models/interview.rb
> +  belongs_to :user
すっかり抜けていました。修正いたします。

2018-04-20 05:37 UTC, pokotyamu commented on db/schema.rb
> +    t.boolean "is_available"
null に暗黙的な状態をもたせるのはあまり良くないと思っています。
false な状態と null を読み手の判断で考えないといけなくなりますよね。
例えば、

```
unless interview.is_available
    拒否のみでやりたい処理
end
```

という場合でも、保留中も処理されてしまいます。

なんで、保留中という状態を明確にする意味でも性別のところで使った enum で対応してみるのはどうでしょうか？

2018-04-20 05:39 UTC, pokotyamu commented on db/schema.rb
> +    t.boolean "is_available"
状態が２つの場合は、 true/false で対応すればいいと思いますが、状態が３つ以上になる時は、排他的な制御の意味でも、 enum などを使うと良さそうです 👍

2018-04-20 11:17 UTC, tkms0106 commented on db/schema.rb
> +    t.boolean "is_available"
nullに役割をもたせると危険なことがよくわかりました。enumに変更いたします。

2018-04-23 04:10 UTC, pokotyamu requested changes
@tkms0106 命名の部分で一点コメント付けています 🙏

2018-04-23 04:10 UTC, pokotyamu commented on app/models/interview.rb
> +  validates :is_available, presence: true
is_available というカラム名だと、２値のままのイメージを持ってしまいますので、`availability` という名前はどうでしょうか？ 🤔 
また、 `to_be` のような接頭語はちょっと冗長な感じがしますね。
保留中という意味で `pending` というのはどうでしょうか？

2018-04-23 22:54 UTC, tkms0106 commented on app/models/interview.rb
> +  validates :is_available, presence: true
- is_available -> 2値のままのイメージ
- to_be_determined -> 冗長

たしかに、その通りだと思いました。候補のご提案もありがとうございます。`availability`と`pending`にリネームします。

2018-04-24 01:34 UTC, pokotyamu commented
コードは良さそう！
改めて動作確認します 👀

2018-04-24 01:38 UTC, pokotyamu commented
うん！動作も良さそう 🙆 
LGTM です 👍 

マージして次に進んで大丈夫です 😄

2018-04-24 12:49 UTC, merged