他ユーザーの面接一覧表示、面接の承認/却下、日付のバリデーション
tkms0106/e-navigator pull request #3
Opened 2018-05-21 11:18 UTC by tkms0106

## やりたかったこと

- 自分以外のユーザー一覧にユーザー情報を表示
  - 名前
  - メールアドレス
  - 年齢
  - 性別
  - 学校名
  - 面接日時
  - 面接一覧へのリンク
- 自分以外の面接一覧では編集・削除リンクを非表示
- 自分以外の面接一覧では未定の日程に対して承認リンクを表示
- 自分以外の面接に対する承認操作を追加
  - 1つの日程を承認すると他の日程は自動的に却下
- 日付のバリデーション
  - 生年月日は過去に限定
  - 面接日程は未来に限定

## やったこと

- EnumHelp Gemを追加
- Users#indexのビューにメールアドレス以外のユーザー情報表示、面接一覧へのリンクを追加
- Interviews#indexで自分自身の場合のみ編集・削除リンクを表示するように変更
- Interviews#indexで他ユーザーの場合のみ承認リンク表示を追加
- 編集・削除リンクと承認リンクをパーシャルに分離
- Interviewsコントローラのapproveアクションとして承認操作を実装
- FutureValidatorとPastValidatorの追加
- Userのdate_of_birthにPastValidatorを適用
- Interviewのscheduled_atにFutureValidatorを適用

## 動作確認方法

- [ ] ユーザーを2アカウント作成（1番ユーザー、2番ユーザーと呼ぶ）
- [ ] 1番ユーザーでログインし、プロフィールを登録
  - [ ] 今日以降の生年月日は登録できないことを確認
- [ ] 2番ユーザーでログインし、1番ユーザーの名前 | メールアドレス | 年齢 | 性別 | 学校名が表示されていることを確認
- [ ] 1番ユーザーでログインし、面接日程を複数作成
  - [ ] 面接一覧で編集・削除リンクが表示されていることを確認
  - [ ] 過去の日時では面接作成できないことを確認
- [ ] 2番ユーザーでログインし、ユーザー一覧ページのリンクから1番ユーザーの面接一覧を表示
  - [ ] 面接一覧で編集・削除リンクが表示されていないことを確認
  - [ ] 面接一覧で承認リンクが表示されていることを確認
- [ ] 日程の1つに対して承認リンクを操作
- [ ] 確認ダイアログでOKを押すと当該日程は承認状態になり、他の日程は自動的に却下状態になることを確認

2018-05-23 02:01 UTC, pokotyamu requested changes
全体的には良さそう！
コメント部分の修正及びコメント返信よろしくお願いします！

2018-05-23 02:01 UTC, pokotyamu commented on app/views/users/index.html.erb
> +          <% if user.interviews.where(is_available: :approval).any? %>
`user.interviews.where(is_available: :approval)`

enum を使っているので、しっかりヘルパー活用していきましょう 👍 
これは以下のように書き直すことができます！

```rb
user.interviews.approval
#=> ユーザーに紐づく approval な面接一覧
interview.approval?
#=> approval な面接なら true
interview.approval!
#=> approval な面接に変える
```

せっかくなんで修正よろしくお願いします！

2018-05-23 02:01 UTC, pokotyamu commented on config/locales/devise.ja.yml
> +        other: "%{count} errors prohibited this %{resource} from being saved:"
ja ファイルなのに、日本語じゃないのか 👀

2018-05-23 02:01 UTC, pokotyamu commented on config/locales/devise.ja.yml
> +        other: "%{count} errors prohibited this %{resource} from being saved:"
これが使えそう。
https://gist.github.com/kaorumori/7276cec9c2d15940a3d93c6fcfab19f3

devise の wiki にまとまってますよ！
[I18n · plataformatec/devise Wiki](https://github.com/plataformatec/devise/wiki/I18n)

2018-05-23 02:01 UTC, pokotyamu commented on config/locales/models/user/ja.yml
> +        pending: 未定
pending いいですね 👍

2018-05-23 02:01 UTC, pokotyamu commented on app/validators/future_validator.rb
> +end
カスタムバリデータいいですね 👍

2018-05-23 02:01 UTC, pokotyamu commented
新規でユーザー作成したタイミングでエラーになってますね 👀 
![image](https://user-images.githubusercontent.com/3479317/40399507-ac573966-5e78-11e8-9c41-783a68c4bb58.png)

2018-05-23 02:06 UTC, pokotyamu commented
【発展(やらなくてもいいです)】
せっかくバリデーションしているので、画面上でもなぜ更新にしっぱいしたのか？みたいな情報出してみるのはどうでしょうか？

2018-05-23 02:08 UTC, pokotyamu commented
rails c で確認してみたのですが、誕生日に10年後(未来)の値を入れると例外発生は良いのですが、翻訳が上手く当たっていないエラーも出ている気がしますね 👀 

```
> User.first.update!(date_of_birth: Time.current + 10.years)
  User Load (0.4ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
Traceback (most recent call last):
        1: from (irb):4
ActiveRecord::RecordInvalid (translation missing: ja.activerecord.errors.messages.record_invalid)
```

2018-05-23 02:12 UTC, pokotyamu commented
一旦レビューに出す前にご自身で動作確認されてますか？ 🤔 
`rails db:reest` などで、データベースに何も入っていない状態から動作確認を通しで一度やってみて、不備がないかの確認をしてから、レビューは出すようにしましょう！

2018-05-28 13:29 UTC, tkms0106 commented on config/locales/devise.ja.yml
> +        other: "%{count} errors prohibited this %{resource} from being saved:"
wikiで紹介のあったdevise-i18n gemを利用する形で日本語化を行いました。

2018-05-28 13:34 UTC, tkms0106 commented on app/views/users/index.html.erb
> +          <% if user.interviews.where(is_available: :approval).any? %>
ヘルパーを使い、簡潔に書き直しました。

2018-05-28 13:36 UTC, tkms0106 commented
>データベースに何も入っていない状態から動作確認を通しで一度

上記、徹底していませんでした。
以後注意します。

2018-05-30 04:37 UTC, pokotyamu commented
📝 前回からの修正分 282daad...2715cee

2018-05-30 04:46 UTC, pokotyamu commented
良さそう 👍 
![image](https://user-images.githubusercontent.com/3479317/40699531-c723b778-640f-11e8-9e59-03d432afa6f1.png)

2018-05-30 04:46 UTC, pokotyamu commented
動作確認も問題なかったです 🙆‍♂️

2018-05-30 04:46 UTC, pokotyamu approved these changes
LGTM です！！！
マージして次に進んじゃってください！！！！！

2018-05-30 11:28 UTC, merged