承認依頼・承認通知メール送信機能の追加
tkms0106/e-navigator pull request #4
Opened 2018-07-02 10:54 UTC by tkms0106

## やりたかったこと

* ユーザーを指定して申請をすると、指定したユーザーに希望する面談日程を承認を依頼するメールを送信
* 承認が押された際に、両者に面接日が決ったことを伝えるメールを送信

## やったこと

* UserMailerの追加
* UserMailerに承認依頼/承認通知メール送信アクションを実装
* 承認依頼メールのhtml/textビューを作成
* 承認通知メールのhtml/textビューを作成
* 承認依頼を行うためのフォーム・アクション・ルーティングを追加
* 承認操作 Interviews#approve に承認通知メール送信処理を追加
* 自分の名前が設定されていない場合は承認依頼・承認操作を実行できないように変更

## 動作確認方法

* 準備
  * [ ] ユーザーを2人作成する
    * それぞれ応募者、採用担当者と呼ぶ
    * この時点では両者ともプロフィールは埋めないでおく
* 確認事項
  * [ ] 応募者でログインし自分の面接日程一覧から承認依頼を試みても、名前を設定していないと承認依頼操作ができないこと
    * [ ] 確認後、応募者プロフィールの名前を設定する（他の項目は任意）
  * [ ] 応募者が面接希望日程を1つも作成していない状態で採用担当者へ承認依頼すると、フラッシュメッセージでメールを送信しなかった旨が伝えられ、実際にメールも送信されないこと
  * [ ] 応募者で日程を1つ以上作成し、採用担当者へ承認依頼を実行すると、採用担当者へメールが届くこと
    * [ ] 承認依頼操作時、プルダウンに応募者自身の宛先は表示されないこと
    * [ ] メール内のリンクから応募者の面接一覧へアクセスできること（要ログイン）
  * [ ] 採用担当者で応募者の面接一覧へアクセスし、承認操作を試みても、失敗すること
    * [ ] 確認後、採用担当者プロフィールの名前を設定する（他の項目は任意）
  * [ ] 採用担当者で応募者の面接一覧へアクセスし、1つの日程に対し承認を行うと、応募者と採用担当者へメールが届くこと
    * [ ] メールには承認され確定した日程が示されていること

2018-07-04 10:13 UTC, pokotyamu requested changes
レビューしましたが結構良い感じですね 👍 
名前つけを中心にコメントしてみました！

2018-07-04 10:13 UTC, pokotyamu commented on app/views/interviews/index.html.erb
> +    <%= collection_select(:user, :id, User.where.not(id: @user.id), :id, :email) %>
ここ View の中で current_user 以外のユーザー一覧をとってくるというのは良くないですね 👀 
Controller から渡してあげる時に、一覧を返してあげましょう！

2018-07-04 10:13 UTC, pokotyamu commented on app/mailers/user_mailer.rb
> +    @interviewer = interviewer
`interviewee` / `interviewer` って名前つけ、めっちゃ良いですね 👍

2018-07-04 10:13 UTC, pokotyamu commented on app/mailers/user_mailer.rb
> +  def approval_notification(interviewee, interviewer, datetime)
notification かぁ。
結構怪しい名前つけなきがします。
何の通知なのか？という意味を付けないと例えば、ユーザーの何かが承認されたことを通知している感じに見えちゃいますね。

2018-07-04 10:13 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +      params.require(:user).permit(:id)
id でも良いけど、 よりわかりやすく interviewer_id とかどうでしょうか？

2018-07-05 11:46 UTC, tkms0106 commented on app/mailers/user_mailer.rb
> +    @interviewer = interviewer
ありがとうございます！

2018-07-05 11:47 UTC, tkms0106 commented on app/views/interviews/index.html.erb
> +    <%= collection_select(:user, :id, User.where.not(id: @user.id), :id, :email) %>
Interviews#indexで準備して渡すようにします。

2018-07-05 11:47 UTC, tkms0106 commented on app/mailers/user_mailer.rb
> +  def approval_notification(interviewee, interviewer, datetime)
ありがとうございます。
`interview_date_decision_notification`
にしようと思います。

2018-07-05 11:49 UTC, tkms0106 commented on app/controllers/interviews_controller.rb
> +      params.require(:user).permit(:id)
ありがとうございます。
`:user` の方を `:interviewer` にしてみることにしました。

2018-07-06 08:46 UTC, pokotyamu commented
変更点概ね良さそうに思いました 👌 

ただ、他ユーザーが誰も居ない状態で、申請を送信しようとすると、エラーになっている気がしますね 🤔 
送れないようにしちゃうのが手っ取り早くて良いと思いました

2018-07-10 01:27 UTC, pokotyamu commented
動作大丈夫そうに思いました 👌 
LGTM 🎉 🎉 🎉 

e-Navigator 完走お疲れ様でした！！！！！

2018-07-10 09:28 UTC, merged